services:
  minitwit:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit_container
    ports:
      - 5035:8080
      - 9091:9091
    volumes:
      - ../data:/app/data
    environment:
      - DbPath=${db_connection}
      - Serilog__WriteTo__0__Args__nodes__0=http://${MONITOR_AND_LOGGING_PRIVATE_IP}:9200