services:
  minitwit:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit_container
    ports:
      - 5035:8080
    volumes:
      - ../data:/app/data
    environment:
      - DbPath=${db_connection}
      - ELASTICSEARCH_URI=http://elasticsearch:9200
    networks:
      - main

  prometheus:
    build: 
      dockerfile: ./Dockerfile
      context: ../monitoring/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    build: 
      dockerfile: ./Dockerfile
      context: ../monitoring/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - main
    volumes:
      - grafana-storage:/var/lib/grafana
      # Save the dasboards to the container, so it can build them.
      - ../monitoring/grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ../monitoring/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ../monitoring/grafana/dashboards:/etc/grafana/dashboards

  elasticsearch:
    container_name: elasticsearch
    build:
      dockerfile: ./Dockerfile
      context: ../logging/elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  elasticsearch-data: {}
  grafana-storage: {}