networks:
  main:
    name: itu-minitwit-network

services:
  minitwit:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-minitwit
      target: final
    networks:
      - main
    ports:
      - 5035:8080
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    environment:
      - DbPath=Server=mysql;Port=3306;Database=minitwit;Uid=root;Pwd=root;SslMode=None;AllowPublicKeyRetrieval=True;
    
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - ./minitwit_db_seed.sql:/docker-entrypoint-initdb.d/seed.sql # Seed the database with some test data
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      # Ensure that database is running and seeded before it is considered healthy
      test: ["CMD-SHELL", "mysql -u root -proot -e 'SELECT 1 FROM minitwit.user LIMIT 1;'"] 
      interval: 5s
      timeout: 5s
      retries: 20
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-tests
    networks:
      - main
    depends_on:
      - minitwit
    environment:
      - BaseUrl=http://minitwit:8080

  apitests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-api-tests
    networks:
      - main
    depends_on:
      - minitwit
    environment:
      - BaseUrl=http://minitwit:8080/api
