networks:
  main:
    name: itu-minitwit-network

services:
  minitwit:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-minitwit
      target: final
    networks:
      main:
        aliases:
          - APP_IP_PLACEHOLDER
    ports:
      - 5035:8080
      - 9091:9091
    depends_on:
      mysql:
        condition: service_healthy
      grafana:
        condition: service_started
      prometheus:
        condition: service_started
    volumes:
      - ./data:/app/data    
    environment:
      - DbPath=Server=mysql;Port=3306;Database=minitwit;Uid=root;Pwd=root;SslMode=None;AllowPublicKeyRetrieval=True;
      - Serilog__WriteTo__0__Args__nodes__0=http://${MONITOR_AND_LOGGING_PRIVATE_IP:-elasticsearch}:9200
  
  # Health check container inspired by: https://lours.me/posts/compose-tip-008-dhi-healthcheck/
  minitwit-health-check:
    image: curlimages/curl
    entrypoint: ["sleep", "infinity"]
    network_mode: "service:minitwit"  # Shares app's network namespace!
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 3s
      retries: 15
      start_period: 10s

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - ./minitwit_db_seed.sql:/docker-entrypoint-initdb.d/seed.sql # Seed the database with some test data
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      # Ensure that database is running and seeded before it is considered healthy
      test: ["CMD-SHELL", "mysql -u root -proot -e 'SELECT 1 FROM minitwit.user LIMIT 1;'"] 
      interval: 5s
      timeout: 5s
      retries: 20
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-tests
    networks:
      - main
    depends_on:
      minitwit-health-check:
        condition: service_healthy
    environment:
      - BaseUrl=http://minitwit:8080

  apitests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-api-tests
    networks:
      - main
    depends_on:
      minitwit-health-check:
        condition: service_healthy
    environment:
      - BaseUrl=http://minitwit:8080/api

  uitests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-ui-tests
    networks:
      - main
    depends_on:
      minitwit-health-check:
        condition: service_healthy
    environment:
      - GUI_URL=http://minitwit:8080/register
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PWD=root
      - DB_NAME=minitwit
      
  prometheus:
    build: 
      dockerfile: ./Dockerfile
      context: ./monitoring/prometheus
    image: prometheus_image
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    build: 
      dockerfile: ./Dockerfile
      context: ./monitoring/grafana
    image: grafana_image
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - main
    volumes:
      - grafana-storage:/var/lib/grafana

      # Save the dasboards to the container, so it can build them.
      - ./monitoring/grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}

  elasticsearch:
    container_name: elasticsearch
    build:
      dockerfile: ./Dockerfile
      context: ./logging/elasticsearch
    ports:
      - 9200:9200
    healthcheck: # Required so es-policy-setup knows when to run
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - main
  es-policy-setup:
    image: curlimages/curl
    container_name: elasticsearch-policy-setup
    networks:
      - main
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: >
      sh -c "
        echo 'Setting up ILM policy...' && 
        curl -X PUT 'http://elasticsearch:9200/_ilm/policy/minitwit-policy' -H 'Content-Type: application/json' -d '{\"policy\":{\"phases\":{\"hot\":{\"actions\":{\"rollover\":{\"max_primary_shard_size\":\"2gb\",\"max_age\":\"7d\"}}},\"delete\":{\"min_age\":\"14d\",\"actions\":{\"delete\":{}}}}}}' && 
        
        echo 'Setting up index template...' && 
        curl -X PUT 'http://elasticsearch:9200/_index_template/minitwit-datastream-template' -H 'Content-Type: application/json' -d '{\"index_patterns\":[\"minitwit-logs*\"],\"data_stream\":{},\"priority\":500,\"template\":{\"settings\":{\"index.lifecycle.name\":\"minitwit-policy\"}}}'
      "

volumes:
  grafana-storage: {}
  elasticsearch-data: {}