networks:
  main:
    name: itu-minitwit-network

services:
  minitwit:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-minitwit
      target: final
    networks:
      - main
    ports:
      - 5035:8080
      - 9091:9090
    depends_on:
      mysql:
        condition: service_healthy
      grafana:
        condition: service_started
      prometheus:
        condition: service_started
    volumes:
      - ./data:/app/data
    environment:
      - DbPath=Server=mysql;Port=3306;Database=minitwit;Uid=root;Pwd=root;SslMode=None;AllowPublicKeyRetrieval=True;
      - ELASTICSEARCH_URI=http://elasticsearch:9200
    
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - ./minitwit_db_seed.sql:/docker-entrypoint-initdb.d/seed.sql # Seed the database with some test data
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      # Ensure that database is running and seeded before it is considered healthy
      test: ["CMD-SHELL", "mysql -u root -proot -e 'SELECT 1 FROM minitwit.user LIMIT 1;'"] 
      interval: 5s
      timeout: 5s
      retries: 20
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-tests
    networks:
      - main
    depends_on:
      - minitwit
    environment:
      - BaseUrl=http://minitwit:8080

  apitests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-api-tests
    networks:
      - main
    depends_on:
      - minitwit
    environment:
      - BaseUrl=http://minitwit:8080/api

  uitests:
    build:
      context: .
      dockerfile: Dockerfile-minitwit-ui-tests
    networks:
      - main
    depends_on:
      - minitwit
    environment:
      - GUI_URL=http://minitwit:8080/register
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PWD=root
      - DB_NAME=minitwit
      
  prometheus:
    build: 
      dockerfile: ./Dockerfile
      context: ./monitoring/prometheus
    image: prometheus_image
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    build: 
      dockerfile: ./Dockerfile
      context: ./monitoring/grafana
    image: grafana_image
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - main
    volumes:
      - grafana-storage:/var/lib/grafana

      # Save the dasboards to the container, so it can build them.
      - ./monitoring/grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards

  elasticsearch:
    container_name: elasticsearch
    build:
      dockerfile: ./Dockerfile
      context: ./logging/elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - main

volumes:
  grafana-storage: {}
  elasticsearch-data: {}