/*
 * Minitwit API
 *
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Text.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;
namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [Route("api")]
    [ApiController]
    public class MinitwitApiController : ControllerBase
    {
      private readonly minitwit.MiniTwit _mt;

      public MinitwitApiController(minitwit.MiniTwit mt)
      {
        _mt = mt;
        _mt.DbPath = "/tmp/minitwit.db";
      }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get list of users followed by the given user.  - Query param &#x60;?no&#x3D;&#x60; limits result count. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("fllws/{username}")]
        [ValidateModelState]
        [EndpointSummary("GetFollow")]
        [ProducesResponseType(statusCode: 200, type: typeof(FollowsResponse), Description = "Success")]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse), Description = "Unauthorized - Must include correct Authorization header")]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse), Description = "User not found (no response body)")]

        public virtual async Task<IActionResult> GetFollow([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {

            if (string.IsNullOrEmpty(authorization) || !authorization.Substring("Basic ".Length).Equals(Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes("simulator:super_safe!"))))
            {
                return BadRequest(new { status = 403, error_msg = "Unauthorized - Must include correct Authorization header" });
            }

            _mt.UpdateLatest(latest);

            if (await _mt.Get_user_id(username) == null)
            {
                return BadRequest(new { status = 404, error_msg = "User not found (no response body)" });
            }
            
            var followed_users = await _mt.Get_followed_users(username, no);

            List<string> follows = [];
            foreach (var user in followed_users)
            {
                follows.Add((string) user["username"]);
            }

            FollowsResponse followsResponse = new FollowsResponse
            {
                Follows = follows
            };

            string followsJSON = followsResponse.ToJson();
            return StatusCode(200, followsJSON);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Returns the latest ID saved</remarks>
        /// <response code="200">Success</response>
        /// <response code="500">Internal Server Error</response>
        [HttpGet]
        [Route("latest")]
        [ValidateModelState]
        [EndpointSummary("GetLatestValue")]
        [ProducesResponseType(statusCode: 200, type: typeof(LatestValue), Description ="Success")]
        [ProducesResponseType(statusCode: 500, type: typeof(ErrorResponse), Description= "Internal Server Error")]
        public virtual IActionResult GetLatestValue()
        {
          int latestValue = _mt.GetLatest();

          return Ok(new LatestValue{Latest = latestValue});
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get recent messages.  - Filters out flagged messages - Returns a list of recent messages (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpGet]
        [Route("msgs")]
        [ValidateModelState]
        [EndpointSummary("GetMessages")]
        [ProducesResponseType(statusCode: 200, type: typeof(List<Message>), Description= "Success")]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse), Description= "Unauthorized - Must include correct Authorization header")]
        public virtual async Task<IActionResult> GetMessages([FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default);

            if (string.IsNullOrEmpty(authorization) || !authorization.Substring("Basic ".Length).Equals(Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes("simulator:super_safe!"))))
            {
                return BadRequest(new { status = 403, error_msg = "Unauthorized - Must include correct Authorization header" });
            }

            _mt.UpdateLatest(latest);

            var messages = await _mt.Get_public_timeline();

            List<Dictionary<string, object>> messagesList = new List<Dictionary<string, object>>();
            foreach (var msg in messages)            {
                if (msg["flagged"].ToString() == "0")
                {
                    var message = new Dictionary<string, object>
                    {
                        ["content"] = msg["text"],
                        ["pub_date"] = msg["pub_date"],
                        ["user"] = msg["username"]
                    };
                    messagesList.Add(message);
                }
            }

            string messagesJSON = JsonSerializer.Serialize(messagesList);
            return StatusCode(200, messagesJSON);

            // string exampleJson = null;
            // exampleJson = "[ {\n  \"pub_date\" : \"2019-12-01 12:00:00\",\n  \"user\" : \"Helge\",\n  \"content\" : \"Hello, World!\"\n}, {\n  \"pub_date\" : \"2019-12-01 12:00:00\",\n  \"user\" : \"Helge\",\n  \"content\" : \"Hello, World!\"\n} ]";
            // exampleJson = "{\n  \"error_msg\" : \"You are not authorized to use this resource!\",\n  \"status\" : 403\n}";
            
            // var example = exampleJson != null
            // ? JsonSerializer.Deserialize<List<Message>>(exampleJson)
            // : default;
            // //TODO: Change the data returned
            // return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get messages for a specific user.  - Returns messages authored by the specified user - Filtered by unflagged - Returns a list of recent messages for the user (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("msgs/{username}")]
        [ValidateModelState]
        [EndpointSummary("GetMessagesPerUser")]
        [ProducesResponseType(statusCode: 200, type: typeof(List<Message>), Description= "Success")]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse), Description= "Unauthorized - Must include correct Authorization header")]
        public virtual async Task<IActionResult> GetMessagesPerUser([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            // string exampleJson = null;
            // exampleJson = "[ {\n  \"pub_date\" : \"2019-12-01 12:00:00\",\n  \"user\" : \"Helge\",\n  \"content\" : \"Hello, World!\"\n}, {\n  \"pub_date\" : \"2019-12-01 12:00:00\",\n  \"user\" : \"Helge\",\n  \"content\" : \"Hello, World!\"\n} ]";
            // exampleJson = "{\n  \"error_msg\" : \"You are not authorized to use this resource!\",\n  \"status\" : 403\n}";
            
            // var example = exampleJson != null
            // ? JsonSerializer.Deserialize<List<Message>>(exampleJson)
            // : default;
            // //TODO: Change the data returned
            // return new ObjectResult(example);

            if (string.IsNullOrEmpty(authorization) || !authorization.Substring("Basic ".Length).Equals(Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes("simulator:super_safe!"))))
            {
                return BadRequest(new { status = 403, error_msg = "Unauthorized - Must include correct Authorization header" });
            }

            _mt.UpdateLatest(latest);

            if (await _mt.Get_user_id(username) == null)
            {
                return NotFound("User not found");
            }

            var usermessages = await _mt.Get_user_timeline(username);

            //Make the messages from the Get_user_timeline function into a list of messages of the form 
            // Message { PubDate = "2019-12-01 12:00:00", User = "Helge", Content = "Hello, World!" }
            // Instead of the form we get from the funcion (Where we get all kinds of other information we don't need) and then serialize it to JSON

            var messagesList = new List<Dictionary<string, object>>();
            foreach (var msg in usermessages)
            {
                if (msg["flagged"].ToString() == "0")
                {
                    var message = new Dictionary<string, object>
                    {
                        ["pub_date"] = msg["pub_date"],
                        ["user"] = msg["username"],
                        ["content"] = msg["text"]
                    };
                    messagesList.Add(message);
                }
            }
            string messagesJSON = JsonSerializer.Serialize(messagesList);

            return StatusCode(200, messagesJSON);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Follow or unfollow a user on behalf of &#x60;username&#x60;.  - Body must contain either &#x60;follow: &lt;user&gt;&#x60; or &#x60;unfollow: &lt;user&gt;&#x60;</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpPost]
        [Route("fllws/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [EndpointSummary("PostFollow")]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse), Description= "Unauthorized - Must include correct Authorization header")]
        public virtual async Task<IActionResult> PostFollow([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromBody]FollowAction payload, [FromQuery (Name = "latest")]int? latest)
        {

             if (string.IsNullOrEmpty(authorization) || !authorization.Substring("Basic ".Length).Equals(Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes("simulator:super_safe!"))))
            {
                return BadRequest(new { status = 403, error_msg = "Unauthorized - Must include correct Authorization header" });
            }
            
            _mt.UpdateLatest(latest);

            if (payload.Follow != null)
            {
                if (await _mt.Get_user_id(payload.Follow) != null)
                {
                    await _mt.Follow_user(username, payload.Follow);
                } else
                {
                    return BadRequest(new { status = 404, error_msg = "User not found" });
                }
            } else if (payload.Unfollow != null)
            {
                if (await _mt.Get_user_id(payload.Unfollow) != null)
                {
                    await _mt.Unfollow_user(username, payload.Unfollow);
                } else
                {
                    return BadRequest(new { status = 404, error_msg = "User not found" });
                }
            }

            return StatusCode(204);

        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Post a new message as a specific user.  - Message must include &#x60;content&#x60; in the body - Stored with timestamp and &#x60;flagged&#x3D;0&#x60; - Returns empty body on success - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpPost]
        [Route("msgs/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [EndpointSummary("PostMessagesPerUser")]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse), Description ="Unauthorized - Must include correct Authorization header")]
        public virtual async Task<IActionResult> PostMessagesPerUser([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromBody]PostMessage payload, [FromQuery (Name = "latest")]int? latest)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);
            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default);

            if (string.IsNullOrEmpty(authorization) || !authorization.Substring("Basic ".Length).Equals(Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes("simulator:super_safe!"))))
            {
                return BadRequest(new { status = 403, error_msg = "Unauthorized - Must include correct Authorization header" });
            }

            _mt.UpdateLatest(latest);

            if (string.IsNullOrEmpty(payload.Content))
            {
                return BadRequest(new { status = 400, error_msg = "You have to enter a message"});
            }
            
            await _mt.Add_Message(username, payload.Content);
            return StatusCode(204);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Register a new user. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="400">Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken</response>
        [HttpPost]
        [Route("register")]
        [Consumes("application/json")]
        [ValidateModelState]
        [EndpointSummary("PostRegister")]
        [ProducesResponseType(statusCode: 400, type: typeof(ErrorResponse), Description ="Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken")]
        public virtual async Task <IActionResult> PostRegister([FromBody]RegisterRequest payload, [FromQuery (Name = "latest")]int? latest)
        {

          //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
          // return StatusCode(204);
          //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
          // return StatusCode(400, default);

          _mt.UpdateLatest(latest);

          if (string.IsNullOrEmpty(payload.Username))
          {
            return BadRequest(new { status = 400, error_msg = "You have to enter a username"});
          }

          if (string.IsNullOrEmpty(payload.Email) || !payload.Email.Contains('@'))
          {
            return BadRequest(new { status = 400, error_msg = "You have to enter a valid email"});
          }

          if (string.IsNullOrEmpty(payload.Pwd))
          {
            return BadRequest(new { status = 400, error_msg = "You have to enter a password"});
          }

          if (await _mt.Get_user_id(payload.Username) != null)
          {
            return BadRequest(new { status = 400, error_msg = "The username is already taken"});
          }

          await _mt.Register(payload.Username, payload.Email, payload.Pwd);

          return StatusCode(204);
        }
    }
}
