{
 "title": "Minitwit_test-Business monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Tweets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_tweets_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tweets in the last 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(minitwit_tweets_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_registrations_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amount of users registrered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(minitwit_registrations_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of HTTP Requests (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}