{
 "title": "Minitwit-test-Connection_status",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"itu-minittwit-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{status=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP requests recieved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "http_requests_received_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Duration of HTTP Requests (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}