services:
  prometheus:
    build: 
      dockerfile: ./Dockerfile
      context: ../monitoring/prometheus
    container_name: prometheus
    ports:
      - "${MONITOR_AND_LOGGING_PRIVATE_IP}:9090:9090"
    networks:
      - main

  grafana:
    build: 
      dockerfile: ./Dockerfile
      context: ../monitoring/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - main
    volumes:
      - grafana-storage:/var/lib/grafana
      # Save the dasboards to the container, so it can build them.
      - ../monitoring/grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ../monitoring/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ../monitoring/grafana/dashboards:/etc/grafana/dashboards

  elasticsearch:
    container_name: elasticsearch
    build:
      dockerfile: ./Dockerfile
      context: ../logging/elasticsearch
    ports:
      - ${MONITOR_AND_LOGGING_PRIVATE_IP}:9200:9200
    healthcheck: # Required so es-policy-setup knows when to run
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - main
  
  es-policy-setup:
    image: curlimages/curl
    container_name: elasticsearch-policy-setup
    networks:
      - main
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: >
      sh -c "
        echo 'Setting up ILM policy...' && 
        curl -X PUT 'http://elasticsearch:9200/_ilm/policy/minitwit-policy' -H 'Content-Type: application/json' -d '{\"policy\":{\"phases\":{\"hot\":{\"actions\":{\"rollover\":{\"max_primary_shard_size\":\"2gb\",\"max_age\":\"7d\"}}},\"delete\":{\"min_age\":\"14d\",\"actions\":{\"delete\":{}}}}}}' && 
        
        echo 'Setting up index template...' && 
        curl -X PUT 'http://elasticsearch:9200/_index_template/minitwit-datastream-template' -H 'Content-Type: application/json' -d '{\"index_patterns\":[\"minitwit-logs*\"],\"data_stream\":{},\"priority\":500,\"template\":{\"settings\":{\"index.lifecycle.name\":\"minitwit-policy\"}}}'
      "

networks:
  main:
    driver: bridge

volumes:
  elasticsearch-data: {}
  grafana-storage: {}