services:
  minitwit:
    image: ${DOCKER_USERNAME}/minitwit-dev
    ports:
      - 5035:8080
      - 9091:9091
    environment:
      - DbPath=${db_connection}
    deploy:
      replicas: 3
      update_config:
        delay: 10s
        order: start-first