services:
  minitwit:
    image: ${DOCKER_USERNAME}/minitwit-dev
    container_name: minitwit_container
    ports:
      - 5035:8080
      - 9091:9091
    volumes:
      - ../data:/app/data
    environment:
      - DbPath=${db_connection}
      - ELASTICSEARCH_URI=http://${MONITOR_AND_LOGGING_PRIVATE_IP}:9200