# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  # This means if i go to localhost:5035 on my own machine, it will forward me to 5035 on the virtual box machine 
  config.vm.network "forwarded_port", guest: 5035, host: 5035
  config.vm.synced_folder ".", "/home/vagrant/vagrant_data", type: "rsync"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
      # 1. Update and install necessary libraries for .NET
      apt-get update # Update package lists (so we get the latest versions of packages and their dependencies)
      apt-get install -y wget curl libicu-dev # Install wget and curl for downloading the installer, and libicu-dev which is a common dependency for .NET on Linux (we might not need all of these, but it's good to have them just in case)

      # 2. Download and run installer as 'vagrant' user
      sudo -u vagrant wget https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh -O /home/vagrant/dotnet-install.sh # Download the installer to the vagrant user's home directory
      chmod +x /home/vagrant/dotnet-install.sh # Make the installer executable
      sudo -u vagrant /home/vagrant/dotnet-install.sh --channel 10.0 # Run the installer as the vagrant user to ensure correct permissions

      # I couldn't really make the following work, because it requires your terminal to be restarted before the changes to
      # the .bashrc file can be seen by the terminal. I think we should delete this
      # 3. Make environment variables permanent for the vagrant user
      #if ! grep -q "DOTNET_ROOT" /home/vagrant/.bashrc; then # Check if DOTNET_ROOT is already set in .bashrc to avoid adding it multiple times (-q for quiet mode)
       #   echo 'export DOTNET_ROOT=$HOME/.dotnet' >> /home/vagrant/.bashrc # Add DOTNET_ROOT to .bashrc 
        #  echo 'export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools' >> /home/vagrant/.bashrc # Add .NET tools to PATH in .bashrc
      #fi

      # Tell the terminal that this is the path where it can find dotnet 
      export DOTNET_ROOT=/home/vagrant/.dotnet

      # Navigate to all the project files
      cd /home/vagrant/vagrant_data/

      # Run the control script with inittmpdb which creates a new empty db in tmp folder
      chmod +x ./control.sh
      ./control.sh inittmpdb

      # Dotnet run the application and use 'nohup' to ensure that the program runs in the background instead of keeping the terminal "alive"
      # Also we need to run it on 0.0.0.0 instead of localhost, because a localhost on a virtual box machine can only be accessed
      # from inside the VM and it cannot be accessed from the outside (from your own machine)
      # Gemini says: 0.0.0.0 tells the app to listen on all available network interfaces, including the one Vagrant 
      # uses to talk to your Mac
      # Would be nice here if we could use the control script, but not sure if possible because Vagrant
      # needs to know the specific path to dotnet (the DOTNET_ROOT) and we don't specify this in control.sh
      # But maybe we should change control.sh like we did for the init tmp db script?
      sudo -u vagrant -E HOME=/home/vagrant nohup $DOTNET_ROOT/dotnet run --urls "http://0.0.0.0:5035" > /home/vagrant/app.log 2>&1 &
      echo "================================================================="
      echo "=                     MiniTwit is running!                      ="
      echo "================================================================="
      echo "Navigate in your browser to:"
      echo "http://localhost:5035"
      # In your own browser, you can navigate to http://localhost:5035 and you will then be forwarded to http://0.0.0.0:5035 on the 
      # virtual machine (but this happens behind the scenes).
  SHELL
end