# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'droplet_kit'

$ip_file = "db_ip.txt"

Vagrant.configure("2") do |config|
  config.vm.box = 'digital_ocean'
  config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
  config.ssh.private_key_path = '~/.ssh/id_ed25519'
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.define "minitwit-2", primary: true do |server|
    server.vm.provider :digital_ocean do |provider|
      provider.ssh_key_name = ENV["SSH_KEY_NAME"]
      provider.token = ENV["DIGITAL_OCEAN_TOKEN"]
      provider.image = 'ubuntu-22-04-x64'
      provider.region = 'fra1'
      provider.size = 's-1vcpu-1gb'
      provider.privatenetworking = true
    end

    server.vm.hostname = "minitwit-2"


    # TRIGGER: Assign the Reserved IP using DropletKit
    server.trigger.after :up do |trigger|
      trigger.info = "Assigning Reserved IP to Droplet..."
      trigger.ruby do |env, machine|
        # Initialize client with your environment token
        client = DropletKit::Client.new(access_token: ENV['DIGITAL_OCEAN_TOKEN'])
        
        # The Reserved IP from your provided image
        reserved_ip = '209.38.114.224' 
        
        # Uses the dynamic ID from Vagrant instead of the hardcoded one
        target_id = machine.id 

        begin
          # The assignment logic from your snippet
          client.reserved_ip_actions.assign(ip: reserved_ip, droplet_id: target_id)
        rescue => e
          puts "Could not assign Reserved IP: #{e.message}"
        end
      end
    end

    # Not sure if all of this trigger stuff is necessary, copied it from Helge's file
    server.trigger.after :up do |trigger|
      trigger.info =  "Writing minitwit's IP to file..."
      trigger.ruby do |env,machine|

        reserved_ip = '209.38.114.224' 

        File.write($ip_file, reserved_ip)
      end
    end

    server.vm.provision "shell", inline: <<-SHELL
      # The following addresses an issue in DO's Ubuntu images, which still contain a lock file
      sudo fuser -vk -TERM /var/lib/apt/lists/lock
      sudo apt-get update
      sudo apt-get install -y wget curl libicu-dev # Install wget and curl for downloading the installer, and libicu-dev which is a common dependency for .NET on Linux (we might not need all of these, but it's good to have them just in case)

      sudo wget https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh #-O /home/vagrant/dotnet-install.sh # Download the installer to the vagrant user's home directory
      pwd
      chmod +x dotnet-install.sh # Make the installer executable
      pwd
      sudo ./dotnet-install.sh --channel 10.0 # Run the installer as the vagrant user to ensure correct permissions

      cp -r /vagrant/* $HOME

      # Run the control script with inittmpdb which creates a new empty db in tmp folder
      chmod +x ./control.sh
      ./control.sh inittmpdb

      sudo nohup .dotnet/dotnet run --urls "http://0.0.0.0:5035" > /app.log 2>&1 &
      #THIS_IP=`hostname -I | cut -d" " -f1`
      echo "http://209.38.114.224:5035"
    SHELL
  end
end