name: Build Report

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra

      - name: Create build directory
        run: mkdir -p report/build

      - name: Run Makefile
        working-directory: ./report
        run: make all

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: report/build/MSc_group_k.pdf